export const projectOneObj = {
  id: "projects",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Project 1",
  headLine: "Smite Api Website",
  description:
    "This is a personal project of a website built using Asp.net MVC model. It is a website for players of popular Hi-Rez Studios Game, Smite, to search themselves and others and see high-level statistics and info pertaining to their account.",
  buttonLabel1: "Code",
  buttonLabel2: "Live",
  imgStart: false,
  img: require("../../videos/SmiteApi.gif").default,
  alt: "project image",
  dark: true,
  primary: true,
  darkText: true,
  codeLink: "https://github.com/ErickBorrero/SmiteApiWebsite",
  liveLink: "https://smiteapi.azurewebsites.net/",
  highlight1: "C# | Asp.Net MVC",
  highlight2: "Consuming public API",
  highlight3: "Bootstrap structuring",
};

export const projectTwoObj = {
  id: "projects",
  lightBg: false,
  lightText: true,
  lightTextDesc: false,
  topLine: "Project 2",
  headLine: "Sorting Visualizer",
  description:
    "This is a personal project where we get to see what happens behind the scenes whenever we need to sort and order through an array of numbers.",
  buttonLabel1: "Code",
  buttonLabel2: "Live",
  imgStart: true,
  img: require("../../videos/SortingVisualizer.gif").default,
  alt: "project image",
  dark: false,
  primary: false,
  darkText: false,
  codeLink: "https://github.com/ErickBorrero/Sorting-Visualizer",
  liveLink: "https://erickborrero.github.io/Sorting-Visualizer/",
  highlight1: "Html/Css/Javascript",
  highlight2: "Computer and Algorithmic Logic/Understanding",
  highlight3: "Canvas Manipulation",
};

export const projectThreeObj = {
  id: "projects",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Project 3",
  headLine: "Personal Portfolio",
  description:
    "This my personal portfolio, showcasing some of my latest work and capabilities.",
  buttonLabel1: "Code",
  buttonLabel2: "Live",
  imgStart: false,
  img: require("../../videos/Portfolio.gif").default,
  alt: "project image",
  dark: true,
  primary: true,
  darkText: true,
  codeLink: "https://github.com/ErickBorrero/ReactPortfolio",
  liveLink: "https://erickborrero.azurewebsites.net",
  highlight1: "React JS (Styled Components)",
  highlight2: "Html/Css/Javascript",
  highlight3: "Azure Web Hosting",
};

export const projectFourObj = {
  id: "projects",
  lightBg: false,
  lightText: true,
  lightTextDesc: false,
  topLine: "Project 4",
  headLine: "AutoLot Database",
  description:
    "This was a class project where we get to interact with the mechanics of a database, using SQL server, and have it displayed to consumers. Currently, the site stands as it was finalized in class, but as time goes on, I will be fleshing out the site to make it presentable.",
  buttonLabel1: "Code",
  buttonLabel2: "Live",
  imgStart: true,
  img: require("../../videos/AutoLot.gif").default,
  alt: "project image",
  dark: false,
  primary: false,
  darkText: false,
  codeLink: "https://github.com/ErickBorrero/C-Sharp-Class-2020/tree/AutoLot",
  liveLink: "https://autolot.azurewebsites.net",
  highlight1: "C# | Asp.Net MVC",
  highlight2: "Entity Framework",
  highlight3: "Sql Server",
};
